
import 'package:Know_your_Food/webclient.dart';
import 'package:connectivity/connectivity.dart';
//import 'package:first_project/model/signinmodel.dart';
import 'package:fluttertoast/fluttertoast.dart';

// import '../Webclient/webclient.dart';
 import '../model/loginmodel.dart';

class Repository {
  Future<LoginModel> checkPhoneNumber(
      {required String url, dynamic data}) async {
    var connectivityResult = await (Connectivity().checkConnectivity());
    if (connectivityResult == ConnectivityResult.none) {
      Fluttertoast.showToast(
        msg: "No internet connection",

        gravity: ToastGravity.CENTER,
      );
    }
    final dynamic response = await WebClient.post(url, data);
    final LoginModel userModel = LoginModel.fromJson(response);
    return userModel;
  }
//     Future<RegistrationModel> signup(
//       {required String url, dynamic data}) async {
//     var connectivityResult = await (Connectivity().checkConnectivity());
//     if (connectivityResult == ConnectivityResult.none) {
//       Fluttertoast.showToast(
//         msg: "No internet connection",

//         gravity: ToastGravity.CENTER,
//       );
//     }
//     final dynamic response = await WebClient.post(url, data);
//     final RegistrationModel userModel = RegistrationModel.fromJson(response);
//     return userModel;
//   }

//      Future<ProfileModel> Profile(
//       {required String url, dynamic data}) async {
//     var connectivityResult = await (Connectivity().checkConnectivity());
//     if (connectivityResult == ConnectivityResult.none) {
//       Fluttertoast.showToast(
//         msg: "No internet connection",

//         gravity: ToastGravity.CENTER,
//       );
//     }
//     final dynamic response = await WebClient.get(url);
//     final ProfileModel userModel = ProfileModel.fromJson(response);
//     return userModel;
//   }

// Future<LoginModel> signin({required String url, dynamic data}) async {
//     var connectivityResult = await (Connectivity().checkConnectivity());
//     if (connectivityResult == ConnectivityResult.none) {
//       Fluttertoast.showToast(
//         msg: "No internet connection",
//         gravity: ToastGravity.CENTER,
//       );
//     } 
//     final dynamic response = await WebClient.post(url, data);
//     final LoginModel userModel = LoginModel.fromJson(response);
//     return userModel;
//   }
  
// //   Future<Autogenerated> generateOtp(
// //       {required String url, dynamic data}) async {
// //     var connectivityResult = await (Connectivity().checkConnectivity());
// //     if (connectivityResult == ConnectivityResult.none) {
// //       Fluttertoast.showToast(
// //         msg: "No internet connection",
// //         toastLength: Toast.LENGTH_SHORT,
// //         gravity: ToastGravity.CENTER,
// //       );
// //     }
// //     final dynamic response = await WebClient.post(url, data);
// //     final Autogenerated generateOtpModel =
// //     Autogenerated.fromJson(response);
// //     return generateOtpModel;
// //   }

// //   Future<Autogenerated> loginWithOtp({required String url, dynamic data}) async {
// //     var connectivityResult = await (Connectivity().checkConnectivity());
// //     if (connectivityResult == ConnectivityResult.none) {
// //       Fluttertoast.showToast(
// //         msg: "No internet connection",
// //         toastLength: Toast.LENGTH_SHORT,
// //         gravity: ToastGravity.CENTER,
// //       );
// //     }
// //     final dynamic response = await WebClient.post(url, data);
// //     final Autogenerated loginModel = Autogenerated.fromJson(response);
// //     return loginModel;
// //   }


 }